//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Levis
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart1
    {
        public string Id { get; set; }
        public Nullable<int> Article_id { get; set; }
        public string Article_name { get; set; }
        public Nullable<double> Article_price { get; set; }
        public Nullable<int> Article_Qty { get; set; }
        public string Article_imagePath { get; set; }
        public string User_Id { get; set; }
    }
}
