//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Levis
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class shopEntities2 : DbContext
    {
        public shopEntities2()
            : base("name=shopEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cart> CartSet { get; set; }
        public virtual DbSet<Article> Article { get; set; }
        public virtual DbSet<Cart1> Cart1Set { get; set; }
        public virtual DbSet<Order> Order { get; set; }
    }
}
