//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Levis
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public Nullable<int> Article_id { get; set; }
        public string Article_Name { get; set; }
        public Nullable<int> User__id { get; set; }
        public string Date { get; set; }
        public Nullable<double> Order_price { get; set; }
    }
}
